### ISSUE TITLE
BCD collision deserializing isn't working on given collision file

### ISSUE THREAD

**Issue by MajorPain1** [vbe0201/kobold#22]
To Recreate:
kobold bcd de collision.bcd

Error:
 ╺━━━━━━━━━━━━━━━━━━━━┅ Backtrace ┅━━━━━━━━━━━━━━━━━━━━╸

 0: ←[1m←[1mError: no variants matched at 0x25faa...←[22m
   ╭───────────────────────┄ Box ┄────────────────────┄
   ┆
   ┆bad magic at 0x25faa: 99
   ╰──────────────────────────────────────────────────┄
   ╭───────────────────────┄ Ray ┄────────────────────┄
   ┆
   ┆bad magic at 0x25faa: 99
   ╰──────────────────────────────────────────────────┄
   ╭───────────────────────┄ Sphere ┄────────────────────┄
   ┆
   ┆bad magic at 0x25faa: 99
   ╰─────────────────────────────────────────────────────┄
   ╭───────────────────────┄ Cylinder ┄────────────────────┄
   ┆
   ┆bad magic at 0x25faa: 99
   ╰───────────────────────────────────────────────────────┄
   ╭───────────────────────┄ Tube ┄────────────────────┄
   ┆
   ┆bad magic at 0x25faa: 99
   ╰───────────────────────────────────────────────────┄
   ╭───────────────────────┄ Plane ┄────────────────────┄
   ┆
   ┆bad magic at 0x25faa: 99
   ╰────────────────────────────────────────────────────┄
   ╭───────────────────────┄ Mesh ┄────────────────────┄
   ┆
   ┆bad magic at 0x25faa: 99
   ╰───────────────────────────────────────────────────┄←[22m
    ...←[1mWhile parsing field 'data' in Shape←[22m←[22m
     at kobold\src\formats\bcd.rs:139
 1: ←[1mWhile parsing field 'shape' in Geometry←[22m
     at kobold\src\formats\bcd.rs:159
 2: ←[1mWhile parsing field 'geometry' in Bcd←[22m
     at kobold\src\formats\bcd.rs:170

Can provide collision file if needed

**Comment by vbe0201** [comment]
Fixed.
